name: Tests

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [2.7, 3.9]
    env:
      CHARON_BASE_URL: http://tracking.database.org
      CHARON_API_TOKEN: charonapitokengoeshere
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install nose pyexcel-xlsx==0.5.8 
        python -m pip install git+https://github.com/SciLifeLab/flowcell_parser.git@master
        python -m pip install git+https://github.com/SciLifeLab/TACA.git@master
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Copy config file
      run: |
        mkdir $HOME/.ngipipeline
        echo foo: bar > $HOME/.ngipipeline/ngi_config.yaml
    - name: Test with nosetests
      run: |
        cd tests && nosetests -v -s utils deliver