language: python

python:
    - "2.7"

before_install:
    - export CHARON_BASE_URL="http://tracking.database.org"
    - export CHARON_API_TOKEN="charonapitokengoeshere"
    - mkdir /home/travis/.ngipipeline
    - "echo foo: bar > /home/travis/.ngipipeline/ngi_config.yaml"
    - pip install setuptools --upgrade
    - pip install pyexcel
    - pip install pyexcel-io==0.6.2
    - pip install traitlets==4.3.3
install:
    - python setup.py install

script:
    - cd tests && nosetests -v -s

notifications:
    email: false
